name: 'Wait a minute...'
author: 'Charles Lechasseur'
description: 'Dismisses PR reviews when the PR diff changes'
runs:
  using: 'node18'
  main: 'dist/index.js'
branding:
  icon: 'alert-circle'
  color: 'blue'
