name: 'Wait a minute...'
author: 'Charles Lechasseur'
description: 'Dismisses PR reviews when the PR diff changes'
inputs:
  github-token:
    description: Value of the GITHUB_TOKEN secret
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'alert-circle'
  color: 'blue'
